language: haskell
compiler: ghc

sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.1

ghc:
  - 7.8

branches:
  only:
    - master
    - release
    - dev

before_install:
  - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2 --enable-coverage
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
