language: haskell
compiler: ghc

ghc:
  - 7.10
  - 7.8

branches:
  only:
    - master
    - release
    - dev

script:
  - cabal install --enable-tests --dependencies-only
  - cabal install stack
  - stack build
  - stack test
  - cabal build
  - cabal test