language: haskell
compiler: ghc

ghc:
  - 7.8

branches:
  only:
    - master
    - release
    - dev

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.22 ghc-7.10.1
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2 --dependencies-only
  - cabal install stack
  - stack build
  - stack test
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist