language: cpp
compiler: clang

branches:
  only:
    - master
    - release
    - dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5-dev
  
script:
  - mkdir build
  - cd build
  - cmake .. -G "Ninja"
  - ninja -j4