language: cpp
compiler: clang

branches:
  only:
    - master
    - release
    - dev

before_install:
  - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev libgtest-dev ninja
  
script:
  - mkdir build
  - cd build
  - cmake .. -G "Ninja"
  - ninja -j4